version: '3.8'

services:
  data-api:
    build: .
    ports:
      - "7438:7438"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7438/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s